Added documentation for Fingertip Visualization
shadow-robot/sr_dexterous_hand_documentation pull request #115
Opened 2022-03-21 14:35 UTC by maxzieba

## Proposed changes

Added documentation for Fingertip Visualization

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [X] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [X] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-03-22 10:07 UTC, bdenoun requested changes

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
I know it's not you, but could you please change setion to section in the "Accessing Data from Hand" please?

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
In "Starting the interface with namespaces", can you change erros to errors please?

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
Same section, each of these fields mean --> means

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
In "Position controller" and "Force controller", paramenters --> parameters

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
In "Force controller > deadband", torgue --> torque and in torque_limit, algoritm --> algorithm

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
In "Hand calibration", misalligments --> misalignments

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +### Fingertip visualization
In "Data visualizer", The check buttons next to each graph name allows you --> allow you

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +The **Visualizer** tab respresents the data in form of tactile points changing their colours based on the value coming from the sensors. In case of a Dexterous Hand equiped with Biotacs as tactile se
respresents --> represents

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +The **Visualizer** tab respresents the data in form of tactile points changing their colours based on the value coming from the sensors. In case of a Dexterous Hand equiped with Biotacs as tactile se
In the case of

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +The **Visualizer** tab respresents the data in form of tactile points changing their colours based on the value coming from the sensors. In case of a Dexterous Hand equiped with Biotacs as tactile se
equipped

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +The **Visualizer** tab respresents the data in form of tactile points changing their colours based on the value coming from the sensors. In case of a Dexterous Hand equiped with Biotacs as tactile se
which will --> that will

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
> +The **Graphs** tab respresents the data in form of plots for all of the data coming from the sensors. Ticking the corresponding checkbox for the datatype will either add or remove the plot from the g
respresents --> represents

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
Still not you, but can you please fix, the read only --> read-only

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
recieved --> received (after - tactile and in - *which_motor_data_arrived*), demensional --> dimensional, refered --> referred

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
in -*idle_time_us* ready for to communicate --> ready to communicate

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In -Biotac, "These topics are read-only and update at 100Hz" --> updated

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
*control_msgs/JointControllerState*, which contain the parameters used for the each joints position controller. --> *control_msgs/JointControllerState*, which contain the parameters used for each joints position controller.

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
They should not be published to directly, but can be accessed through rqt_reconfigure. --> They should not be published directly but can be accessed through rqt_reconfigure.

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In "Changing motor data update rates", in a file which you --> in a file that you can edit

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In SrRobotCommander > Overview, descriptions --> descriptions

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In "Basic terminology", which are --> that are, predifined --> predefined, high leveler --> higher level

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In Getting basic information, predifined --> predefined

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In Settings functions, stops the the trajectory --> the trajectory

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
In Example, predifined -> predefined

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
way point --> waypoint

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
Go the 'Planning ' tab --> Go to the 'Planning'

2022-03-22 10:07 UTC, bdenoun commented on docs/user_guide/3_software_description.md
>  ## Command line interface
allows user --> allows users (multiple occurences)

2022-03-23 09:31 UTC, bdenoun approved these changes

2022-03-24 13:49 UTC, giusebar approved these changes

2022-03-25 10:27 UTC, merged