Updating changelog v.1.0.15
shadow-robot/sr_dexterous_hand_documentation pull request #134
Opened 2022-06-20 16:17 UTC by jeferrandiz98

## Proposed changes

Updating changelog with version 1.0.15
## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-06-20 16:27 UTC, maxzieba requested changes

2022-06-20 16:27 UTC, maxzieba commented on docs/user_guide/5_changelog.md
> +* Fix linter errors
Remove repeating of 'fix linter errors'

2022-06-20 16:27 UTC, maxzieba commented on docs/user_guide/5_changelog.md
> +* Do not require ur_description unless it is neededSupport workspaces without UR components.
I think this should be split into 2 line or should be more clear (check the corresponding link from Confluence)

2022-06-21 07:34 UTC, bdenoun approved these changes
After Max's comments are addressed

2022-06-21 08:20 UTC, maxzieba approved these changes

2022-06-28 14:21 UTC, biofotis approved these changes

2022-06-28 14:21 UTC, merged