Updating hand documentation
shadow-robot/sr_dexterous_hand_documentation pull request #158
Opened 2023-06-02 13:48 UTC by georgiablanco

## Proposed changes

Updating hand documentation from feedback

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2023-06-06 08:24 UTC, jeferal approved these changes

2023-06-07 16:36 UTC, beatrizleon requested changes

2023-06-07 16:36 UTC, beatrizleon commented on docs/index.rst
> +* :doc:`/user_guide/mh_re_installing_the_software`
I dont think you need to change that here, as you haven't renamed the file. Inside it you can change the title as you have done.

2023-06-07 16:36 UTC, beatrizleon commented on docs/user_guide/fc_FAQ.rst
> +If the Hand is connected, you should see a message saying that a Hand is connected and the ethernet adapter it is connected to. If the Hand is not connected, you will see a message saying that no Han
```suggestion
If the Hand is connected, you should see a message saying that a Hand is connected and the ethernet adapter is connected to. If the Hand is not connected, you will see a message saying that no Hand is detected. If this is the case, unplug and replug the Ethernet cable and Power cycle the hand and try again.
```

2023-06-07 16:36 UTC, beatrizleon commented on docs/user_guide/sd_command_line.rst
> +  This topic can be published to and is the set position for the wwrist trajectory controller. It comprises an array of all the joints set positions and is used for commanding the robot. For example
```suggestion
  This topic can be published to and is the set position for the wrist trajectory controller. It comprises an array of all the joints set positions and is used for commanding the robot. For example the rqt joint sliders publish to it.
```

2023-06-07 16:42 UTC, beatrizleon commented on docs/index.rst
> +* :doc:`/user_guide/mh_re_installing_the_software`
you also need to change this in line 187

2023-06-07 16:43 UTC, beatrizleon commented
I added a few comments. Also we need to solve the conflicst.

2023-06-13 11:59 UTC, beatrizleon approved these changes

2023-06-13 12:53 UTC, merged