updating ethercat_interface variable to ethercat_right_hand
shadow-robot/sr_dexterous_hand_documentation pull request #77
Opened 2020-11-09 15:03 UTC by georgiablanco

2020-11-09 15:22 UTC, biofotis approved these changes

2020-11-10 14:39 UTC, mikramarc requested changes

2020-11-10 14:39 UTC, mikramarc commented on docs/user_guide/1_2_3_installing_the_software_uni.rst
> +     bash <(curl -Ls bit.ly/run-aurora) server_and_nuc_deploy --read-secure customer_key ethercat_left_hand=<ethercat_right_hand> config_branch=<config_branch> product=<product> reinstall=true upgrad
one says left, one right

2020-11-10 14:49 UTC, mikramarc approved these changes

2020-11-10 14:49 UTC, merged